name: e_commerce_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  flutter_redux: ^0.10.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  http: ^0.13.6
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  redux: ^5.0.0
  cloud_firestore: ^4.5.1
  cached_network_image: ^3.2.3
  collection: ^1.15.2
  animate_gradient: ^0.0.2+1
  flutter_locker: ^2.1.2
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5
  url_launcher: ^6.0.0
  flutter_phone_direct_caller: ^2.1.1
  open_mail_app: ^0.4.5
  uuid: ^4.1.0
  coupon_uikit: ^0.2.0
  getwidget: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
